import type { BunPlugin } from "bun";
import { basename, dirname, relative, resolve as resolvePath } from "path";
import { parseMDX } from "./src/parser";
import { compile } from "./src/compiler";

function toPosixPath(value: string): string {
  return value.replace(/\\/g, "/");
}

function makeRelativePath(from: string, to: string): string {
  let relativePath = toPosixPath(relative(from, to));
  if (!relativePath) {
    relativePath = toPosixPath(basename(to));
  }

  if (!relativePath.startsWith(".")) {
    relativePath = `./${relativePath}`;
  }

  return relativePath;
}

export const betterMDXPlugin: BunPlugin = {
  name: "better-mdx-loader",
  setup(build) {
    const projectRoot = build.config.root ? resolvePath(build.config.root) : process.cwd();

    build.onResolve({ filter: /\.mdx$/ }, args => {
      const importerDir = args.importer ? dirname(args.importer) : projectRoot;
      const resolvedPath = resolvePath(importerDir, args.path);
      return { path: resolvedPath };
    });

    build.onLoad({ filter: /\.mdx$/ }, async args => {
      const filePath = args.path;
      const source = await Bun.file(filePath).text();

      let parsed;
      let compiled;
      try {
        parsed = parseMDX(source);
        compiled = compile(parsed);
      } catch (error) {
        const reason = error instanceof Error ? error.message : String(error);
        throw new Error(`[better-mdx-loader] Failed to compile ${filePath}: ${reason}`);
      }

      const moduleDir = dirname(filePath);
      const rendererImportPath = makeRelativePath(moduleDir, resolvePath(projectRoot, "src/renderer.ts"));
      const compilerImportPath = makeRelativePath(moduleDir, resolvePath(projectRoot, "src/compiler.ts"));
      const compiledJson = JSON.stringify(compiled, null, 2);
      const importsJson = JSON.stringify(parsed.imports, null, 2);

      const contents = `// Generated by better-mdx bun loader for ${toPosixPath(filePath)}
import { render as __better_mdx_render, type RenderedResult } from "${rendererImportPath}";
import type { CompiledMDX } from "${compilerImportPath}";

const __better_mdx_compiled: CompiledMDX = ${compiledJson};

export const metadata = __better_mdx_compiled.metadata;
export const template = __better_mdx_compiled.template;
export const typescript = __better_mdx_compiled.typescript;
export const dependencies = __better_mdx_compiled.dependencies;
export const id = __better_mdx_compiled.id;
export const filename = ${JSON.stringify(filePath)};
export const defaultBasePath = ${JSON.stringify(moduleDir)};
export const sourceImports = ${importsJson};
export const source = ${JSON.stringify(source)};

export async function render(context = {}, props = {}, basePath = defaultBasePath): Promise<RenderedResult> {
  return __better_mdx_render(__better_mdx_compiled, context, props, basePath);
}

export function getCompiled(): CompiledMDX {
  return __better_mdx_compiled;
}

export default __better_mdx_compiled;
`;

      return {
        loader: "ts",
        contents,
      };
    });
  },
};

export default betterMDXPlugin;
